<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PharmaFlow.Tests.Architecture</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PharmaFlow.Application\PharmaFlow.Application.csproj" />
  </ItemGroup>

</Project>
