// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmaFlow.Infrastructure.Persistence;

#nullable disable

namespace PharmaFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508040110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmaFlow.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActorRoleAtTime")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("actor_role_at_time");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterStateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state_json");

                    b.Property<string>("BeforeStateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state_json");

                    b.Property<string>("ClientInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_info");

                    b.Property<string>("EventPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("event_payload_hash")
                        .IsFixedLength();

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousEventHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("previous_event_hash")
                        .IsFixedLength();

                    b.Property<string>("ReasonForChange")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_for_change");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("source_ip_address");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_entity_id");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_events_actor_user_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_audit_events_event_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.HasIndex("PreviousEventHash")
                        .HasDatabaseName("ix_audit_events_previous_event_hash");

                    b.HasIndex("TargetEntityType", "TargetEntityId")
                        .HasDatabaseName("ix_audit_events_target_entity_type_target_entity_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Participants.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EnrolmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrolment_date");

                    b.Property<string>("EnrolmentStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("enrolment_status");

                    b.Property<string>("Initials")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("initials");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly?>("ScreeningDate")
                        .HasColumnType("date")
                        .HasColumnName("screening_date");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sex");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SubjectNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("subject_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly?>("WithdrawalDate")
                        .HasColumnType("date")
                        .HasColumnName("withdrawal_date");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("withdrawal_reason");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_birth");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("EnrolmentStatus")
                        .HasDatabaseName("ix_participants_enrolment_status");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_participants_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_participants_site_id");

                    b.HasIndex("SiteId", "SubjectNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_participants_site_id_subject_number");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Signatures.SignatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("authentication_method");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip");

                    b.Property<bool>("ContinuousSession")
                        .HasColumnType("boolean")
                        .HasColumnName("continuous_session");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meaning");

                    b.Property<string>("MfaMethod")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("mfa_method");

                    b.Property<string>("PreviousSignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("previous_signature_hash")
                        .IsFixedLength();

                    b.Property<string>("ReasonStatement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_statement");

                    b.Property<string>("SignaturePayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("signature_payload_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("signer_user_id");

                    b.Property<string>("SigningKeyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signing_key_id");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_entity_id");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_entity_type");

                    b.Property<string>("TargetVersionOrHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_version_or_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_signature_records");

                    b.HasIndex("Meaning")
                        .HasDatabaseName("ix_signature_records_meaning");

                    b.HasIndex("PreviousSignatureHash")
                        .HasDatabaseName("ix_signature_records_previous_signature_hash");

                    b.HasIndex("SignedAt")
                        .HasDatabaseName("ix_signature_records_signed_at");

                    b.HasIndex("SignerUserId")
                        .HasDatabaseName("ix_signature_records_signer_user_id");

                    b.HasIndex("TargetEntityType", "TargetEntityId")
                        .HasDatabaseName("ix_signature_records_target_entity_type_target_entity_id");

                    b.ToTable("signature_records", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activation_date");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrincipalInvestigatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_investigator_user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("site_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_sites_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("PrincipalInvestigatorUserId")
                        .HasDatabaseName("ix_sites_principal_investigator_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sites_status");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_sites_study_id");

                    b.HasIndex("StudyId", "SiteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_study_id_site_number");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Studies.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("phase");

                    b.Property<DateOnly>("PlannedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_end_date");

                    b.Property<int>("PlannedEnrolment")
                        .HasColumnType("integer")
                        .HasColumnName("planned_enrolment");

                    b.Property<DateOnly>("PlannedStartDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_start_date");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocol_number");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SponsorOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sponsor_organization");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TherapeuticArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("therapeutic_area");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_studies");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_studies_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_studies_protocol_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_studies_status");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Users.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBySignatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_signature_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_assignments");

                    b.HasIndex("EndedAt")
                        .HasDatabaseName("ix_role_assignments_ended_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_role_assignments_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_role_assignments_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_assignments_user_id");

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayTitle")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_title");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MfaEnrolled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enrolled");

                    b.Property<DateTimeOffset?>("PasswordLastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_last_changed_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PharmaFlow.Domain.Users.RoleAssignment", b =>
                {
                    b.OwnsOne("PharmaFlow.Domain.Users.Scope", "Scope", b1 =>
                        {
                            b1.Property<Guid>("RoleAssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("scope_kind");

                            b1.Property<Guid?>("SiteId")
                                .HasColumnType("uuid")
                                .HasColumnName("scope_site_id");

                            b1.Property<Guid?>("StudyId")
                                .HasColumnType("uuid")
                                .HasColumnName("scope_study_id");

                            b1.HasKey("RoleAssignmentId");

                            b1.ToTable("role_assignments");

                            b1.WithOwner()
                                .HasForeignKey("RoleAssignmentId")
                                .HasConstraintName("fk_role_assignments_role_assignments_id");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
