<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmaFlow.Domain\PharmaFlow.Domain.csproj" />
    <ProjectReference Include="..\PharmaFlow.Application\PharmaFlow.Application.csproj" />
    <ProjectReference Include="..\PharmaFlow.Infrastructure\PharmaFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
