<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PharmaFlow.Application\PharmaFlow.Application.csproj" />
    <ProjectReference Include="..\PharmaFlow.Domain\PharmaFlow.Domain.csproj" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>

</Project>
