-- ============================================================================
-- Legacy "dbo" schema — simulated inherited core-banking database.
--
-- This stands in for the ~10-year-old SQL Server system PharmaFlow's fintech
-- pivot is modernising. It lives in the SAME Postgres instance under a `dbo`
-- schema purely to mimic the SQL Server feel; PharmaFlow's own domain stays in
-- `public`. The stored functions here (fn_*) hold business logic that S8 ports
-- into tested C# and then retires. EF does not own these tables — they are
-- applied as a raw script and mapped read-only (ExcludeFromMigrations) on the
-- consuming side.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS dbo;

-- ---------------------------------------------------------------------------
-- Core deposit-banking tables
-- ---------------------------------------------------------------------------

CREATE TABLE dbo.customer (
    customer_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(200) NOT NULL,
    segment       varchar(20)  NOT NULL,                 -- RETAIL / SME / PRIVATE
    created_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE dbo.account (
    account_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint       NOT NULL REFERENCES dbo.customer(customer_id),
    account_no    varchar(20)  NOT NULL UNIQUE,
    account_type  varchar(20)  NOT NULL,                 -- CHECKING / SAVINGS
    currency      char(3)      NOT NULL DEFAULT 'USD',
    status        varchar(10)  NOT NULL DEFAULT 'OPEN',  -- OPEN / DORMANT / CLOSED
    opened_on     date         NOT NULL,
    closed_on     date
);

-- Posting date vs value date is deliberate: a txn is booked (posted_at) on one
-- day but takes effect for balance/interest (value_date) on another — the classic
-- weekend / cut-off gap. Balances are value-dated; amount is signed (credit +, debit -).
CREATE TABLE dbo.account_txn (
    txn_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    bigint        NOT NULL REFERENCES dbo.account(account_id),
    posted_at     timestamptz   NOT NULL,
    value_date    date          NOT NULL,
    amount        numeric(19,4) NOT NULL,
    txn_type      varchar(20)   NOT NULL,                -- DEPOSIT / WITHDRAWAL / FEE / INTEREST / TRANSFER
    description   varchar(200)
);

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

-- Effective-dated, tiered interest. A rate applies from effective_from onward to
-- balances at/above balance_floor; the highest matching floor wins. Rates change
-- mid-period, so accrual must split the period at each effective_from break.
CREATE TABLE dbo.interest_rate_tier (
    rate_tier_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type   varchar(20)   NOT NULL,
    effective_from date          NOT NULL,
    balance_floor  numeric(19,4) NOT NULL,               -- tier applies when balance >= floor
    annual_rate    numeric(9,6)  NOT NULL                -- 0.025000 = 2.5% p.a.
);

-- Monthly maintenance fee rules per account type.
CREATE TABLE dbo.fee_schedule (
    fee_schedule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type    varchar(20)   NOT NULL UNIQUE,
    monthly_fee     numeric(19,4) NOT NULL,
    min_avg_balance numeric(19,4) NOT NULL,              -- waive monthly_fee if ADB >= this
    free_txn_count  int           NOT NULL,              -- per-txn fee applies beyond this count
    per_txn_fee     numeric(19,4) NOT NULL
);

-- ---------------------------------------------------------------------------
-- Lending tables (for the payment-waterfall function)
-- ---------------------------------------------------------------------------

CREATE TABLE dbo.loan (
    loan_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint        NOT NULL REFERENCES dbo.customer(customer_id),
    principal     numeric(19,4) NOT NULL,
    annual_rate   numeric(9,6)  NOT NULL,
    day_count     varchar(10)   NOT NULL DEFAULT 'ACT/365',
    penalty_rate  numeric(9,6)  NOT NULL DEFAULT 0.180000, -- annual penalty rate on overdue balance
    late_fee      numeric(19,4) NOT NULL DEFAULT 25.0000,  -- flat fee per overdue installment, assessed once
    opened_on     date          NOT NULL,
    status        varchar(10)   NOT NULL DEFAULT 'ACTIVE'   -- ACTIVE / CLOSED / WRITTEN_OFF
);

-- One row per scheduled installment. *_due are the originally scheduled amounts;
-- *_paid accumulate as payments are allocated. penalty_accrued grows for overdue
-- installments; last_accrued_on tracks the through-date of that accrual.
CREATE TABLE dbo.loan_installment (
    installment_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id         bigint        NOT NULL REFERENCES dbo.loan(loan_id),
    seq_no          int           NOT NULL,
    due_date        date          NOT NULL,
    principal_due   numeric(19,4) NOT NULL,
    interest_due    numeric(19,4) NOT NULL,
    fee_due         numeric(19,4) NOT NULL DEFAULT 0,
    principal_paid  numeric(19,4) NOT NULL DEFAULT 0,
    interest_paid   numeric(19,4) NOT NULL DEFAULT 0,
    fee_paid        numeric(19,4) NOT NULL DEFAULT 0,
    penalty_accrued numeric(19,4) NOT NULL DEFAULT 0,
    penalty_paid    numeric(19,4) NOT NULL DEFAULT 0,
    last_accrued_on date,
    status          varchar(10)   NOT NULL DEFAULT 'DUE',  -- DUE / PARTIAL / PAID
    UNIQUE (loan_id, seq_no)
);

CREATE TABLE dbo.loan_payment (
    payment_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id       bigint        NOT NULL REFERENCES dbo.loan(loan_id),
    paid_on       date          NOT NULL,
    amount        numeric(19,4) NOT NULL
);

-- The waterfall's output: how each payment was split, per installment and bucket.
CREATE TABLE dbo.loan_payment_alloc (
    alloc_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id     bigint        NOT NULL REFERENCES dbo.loan_payment(payment_id),
    installment_id bigint        NOT NULL REFERENCES dbo.loan_installment(installment_id),
    bucket         varchar(10)   NOT NULL,                -- FEE / PENALTY / INTEREST / PRINCIPAL
    amount         numeric(19,4) NOT NULL
);

CREATE INDEX ix_account_txn_account_value ON dbo.account_txn (account_id, value_date, txn_id);
CREATE INDEX ix_loan_installment_loan_seq ON dbo.loan_installment (loan_id, seq_no);
